### ISSUE TITLE
Cannot see the thumbnail 

### ISSUE THREAD

**Issue by Lizhz** [Dhaval2404/material-icon-generator-plugin#3]
when opened the plugin, the thumbnail of the icon did not show

**Comment by Dhaval2404** [comment]
@Lizhz It seems to be working fine for me. Are you facing issues with any particular icon or all icons?

Also, The plugin requires a working internet connection to fetch the icons.

**Comment by Lizhz** [comment]
@Dhaval2404 ,It seems caused by the network problem
